"""Initial migration

Revision ID: 59d29a2e9481
Revises: 
Create Date: 2025-05-15 14:00:51.118936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59d29a2e9481'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classification_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ifc_class', sa.String(), nullable=False),
    sa.Column('predefined_type', sa.String(), nullable=True),
    sa.Column('target_category', sa.String(), nullable=False),
    sa.Column('bac_twin_code', sa.String(), nullable=True),
    sa.Column('amev_code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('distribution_systems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('predefined_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ifc_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('storey_id', sa.Integer(), nullable=True),
    sa.Column('storey_name', sa.String(), nullable=True),
    sa.Column('space_id', sa.Integer(), nullable=True),
    sa.Column('space_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hvac_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('global_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('ifc_class', sa.String(), nullable=False),
    sa.Column('object_type', sa.String(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('is_electronic', sa.Boolean(), nullable=True),
    sa.Column('bas_code', sa.String(), nullable=True),
    sa.Column('bas_standard', sa.String(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('system_id', sa.Integer(), nullable=True),
    sa.Column('mapping_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['mapping_id'], ['classification_mappings.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['ifc_models.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['distribution_systems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('global_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hvac_components')
    op.drop_table('locations')
    op.drop_table('ifc_models')
    op.drop_table('distribution_systems')
    op.drop_table('classification_mappings')
    # ### end Alembic commands ###
